/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 02-Nov-2017 16:43:38 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'Asset'
;

DROP TABLE IF EXISTS 'Derivative_Instrument_Dynamic'
;

DROP TABLE IF EXISTS 'Economic_Resource_Fixed_Income'
;

DROP TABLE IF EXISTS 'Economic_Resource_Risky_Income'
;

DROP TABLE IF EXISTS 'Liability'
;

DROP TABLE IF EXISTS 'Off_Balance'
;

DROP TABLE IF EXISTS 'Stock_Derivative_Static'
;

DROP TABLE IF EXISTS 'Stock_Information_Static'
;

DROP TABLE IF EXISTS 'Stock_Pricing_Dynamic'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'Asset'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY,
	'timestamp' TEXT NOT NULL,
	'Fair_Value' REAL NOT NULL,
	CONSTRAINT 'FK_Asset_Derivative_Instrument' FOREIGN KEY ('Derivative_Instrument_Dynamic_ID') REFERENCES 'Derivative_Instrument_Dynamic' ('Derivative_Instrument_Dynamic_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Derivative_Instrument_Dynamic'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'Stock_Derivative_Static_ID' INTEGER NOT NULL,
	'timestamp' TEXT NOT NULL,
	'Fair_Value' REAL NOT NULL,
	CONSTRAINT 'FK_Derivative_Instrument_Stock_Derivative' FOREIGN KEY ('Stock_Derivative_Static_ID') REFERENCES 'Stock_Derivative_Static' ('Stock_Derivative_Static_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Economic_Resource_Fixed_Income'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY,
	'timestamp' TEXT NOT NULL,
	'Present_Value' REAL NOT NULL,
	'Asset_Or_Liability' INTEGER NULL,
	CONSTRAINT 'FK_Economic_Resource_Fixed_Income_Derivative_Instrument' FOREIGN KEY ('Derivative_Instrument_Dynamic_ID') REFERENCES 'Derivative_Instrument_Dynamic' ('Derivative_Instrument_Dynamic_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Economic_Resource_Risky_Income'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY,
	'timestamp' TEXT NOT NULL,
	'Nd1t' REAL NULL,
	'Value' REAL NOT NULL,
	'Asset_Or_Liability' INTEGER NULL,
	CONSTRAINT 'FK_Economic_Resource_Risky_Income_Derivative_Instrument' FOREIGN KEY ('Derivative_Instrument_Dynamic_ID') REFERENCES 'Derivative_Instrument_Dynamic' ('Derivative_Instrument_Dynamic_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Liability'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY,
	'timestamp' TEXT NOT NULL,
	'Fair_Value' REAL NOT NULL,
	CONSTRAINT 'FK_Liability_Derivative_Instrument' FOREIGN KEY ('Derivative_Instrument_Dynamic_ID') REFERENCES 'Derivative_Instrument_Dynamic' ('Derivative_Instrument_Dynamic_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Off_Balance'
(
	'Derivative_Instrument_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY,
	'timestamp' TEXT NOT NULL,
	CONSTRAINT 'FK_Off_Balance_Derivative_Instrument' FOREIGN KEY ('Derivative_Instrument_Dynamic_ID') REFERENCES 'Derivative_Instrument_Dynamic' ('Derivative_Instrument_Dynamic_ID') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Stock_Derivative_Static'
(
	'Stock_Derivative_Static_ID' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'Type_Of_Stock_Derivative' INTEGER NULL,
	'Stock_ISIN' TEXT NOT NULL,
	'Exercise_Or_Forward_Price' REAL NOT NULL,
	'Contracting_Date' TEXT NOT NULL,
	'Expiration_Date' TEXT NOT NULL,
	'Contract_Size' REAL NULL,
	'Number_Of_Contracts' REAL NULL,
	'Stock_Volatility' REAL NOT NULL,
	'Interest_Rate' REAL NOT NULL,
	'Mark_To_Model' INTEGER NULL,
	CONSTRAINT 'FK_Stock_Derivative_Stock_Information' FOREIGN KEY ('Stock_ISIN') REFERENCES 'Stock_Information_Static' ('Stock_ISIN') ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE 'Stock_Information_Static'
(
	'Stock_ISIN' TEXT NOT NULL PRIMARY KEY,
	'Stock_Description' TEXT NULL
)
;

CREATE TABLE 'Stock_Pricing_Dynamic'
(
	'Stock_Pricing_Dynamic_ID' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'Stock_ISIN' TEXT NOT NULL,
	'Stock_Price' REAL NOT NULL,
	'timestamp' TEXT NOT NULL,
	CONSTRAINT 'FK_Stock_Pricing_Dynamic_Stock_Information_Static' FOREIGN KEY ('Stock_ISIN') REFERENCES 'Stock_Information_Static' ('Stock_ISIN') ON DELETE No Action ON UPDATE No Action
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_Asset_Derivative_Instrument'
 ON 'Asset' ('Derivative_Instrument_Dynamic_ID' ASC)
;

CREATE INDEX 'IXFK_Derivative_Instrument_Stock_Derivative'
 ON 'Derivative_Instrument_Dynamic' ('Stock_Derivative_Static_ID' ASC)
;

CREATE INDEX 'IXFK_Economic_Resource_Fixed_Income_Derivative_Instrument'
 ON 'Economic_Resource_Fixed_Income' ('Derivative_Instrument_Dynamic_ID' ASC)
;

CREATE INDEX 'IXFK_Economic_Resource_Risky_Income_Derivative_Instrument'
 ON 'Economic_Resource_Risky_Income' ('Derivative_Instrument_Dynamic_ID' ASC)
;

CREATE INDEX 'IXFK_Liability_Derivative_Instrument'
 ON 'Liability' ('Derivative_Instrument_Dynamic_ID' ASC)
;

CREATE INDEX 'IXFK_Off_Balance_Derivative_Instrument'
 ON 'Off_Balance' ('Derivative_Instrument_Dynamic_ID' ASC)
;

CREATE INDEX 'IXFK_Stock_Derivative_Stock_Information'
 ON 'Stock_Derivative_Static' ('Stock_ISIN' ASC)
;

CREATE INDEX 'IXFK_Stock_Pricing_Dynamic_Stock_Information_Static'
 ON 'Stock_Pricing_Dynamic' ('Stock_ISIN' ASC)
;

CREATE INDEX 'IXFK_Stock_Pricing_Stock_Information'
 ON 'Stock_Pricing_Dynamic' ('Stock_ISIN' ASC)
;
